# This file was generated by the {rix} R package v0.9.1 on 2024-08-25
# with following call:
# >rix(r_ver = "ae815cee91b417be55d43781eb4b73ae1ecc396c",
#  > r_pkgs = c("tidyverse",
#  > "targets",
#  > "devtools",
#  > "testthat",
#  > "tarchetypes",
#  > "rmarkdown",
#  > "openxlsx",
#  > "readxl"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "rstudio",
#  > project_path = "~/shellfactory/",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision ae815cee91b417be55d43781eb4b73ae1ecc396c for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/ae815cee91b417be55d43781eb4b73ae1ecc396c.tar.gz") {};
 
  rpkgs = with pkgs.rPackages; [
      tidyverse
      targets
      devtools
      testthat
      tarchetypes
      rmarkdown
      openxlsx
      readxl
      codetools # dependecy for rix
      curl      # dependecy for rix
      jsonlite  # dependecy for rix
      sys       # dependecy for rix
  ];


  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      glibcLocales
      nix;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [  rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages  wrapped_pkgs ];
  
}
